{
 "title": "KubeDoor - K8S节点资源实时监控",
 "description": "KubeDoor - K8S节点资源实时监控",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn",
  "KubeDoor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ext_key", "label": "external_labels_key", "query": "__PROM_K8S_TAG_KEY__" },
   {
    "name": "ext_value",
    "label": "K8S",
    "query": {
     "query": "label_values(node_uname_info,$ext_key)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(node_uname_info{$ext_key=~\"$ext_value\"},nodename)"
    }
   },
   {
    "name": "instance",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{$ext_key=~\"$ext_value\", nodename=~\"$name\"},instance)"
    }
   },
   { "name": "interval", "label": "间隔", "query": "3m" },
   {
    "name": "total",
    "label": "主机数",
    "query": {
     "query": "query_result(count(node_uname_info{$ext_key=~\"$ext_value\"}))"
    }
   },
   {
    "name": "device",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{$ext_key=~\"$ext_value\", instance=~\"$instance\", device!~\"tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*|flannel.*\"},device)"
    }
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": {
     "query": "query_result(topk(1,sort_desc(max(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",instance=~\"$instance\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_name",
    "label": "展示使用的名称",
    "query": {
     "query": "label_values(node_uname_info{$ext_key=~\"$ext_value\", nodename=~\"$name\", instance=~\"$instance\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🏡资源总览【K8S：$ext_value】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "服务器资源总览表【主机总数：$total】",
   "type": "table",
   "description": "标记*字段解释：\n注意： 分区默认只统计ext?和XFS格式的分区。\n- 最大分区：该主机最大的分区的总容量\n- 最大分区使用率：总容量最大的那个分区的磁盘使用率\n- 最大使用率：磁盘使用率最高的那个分区的磁盘使用率\n- IOutil使用率：IOutil最大的那个分区的磁盘IOutil\n- 磁盘读写：读写最大的那个分区的磁盘读写速度\n- 网络上下载带宽：带宽使用最多的那个网卡的带宽使用量\n\n- 连接数：状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n- TCPtw：等待关闭的TCP连接数\n\n健康值是一个新增的指标：\n- 根据CPU，内存，IO计算出来的一个值，低于90分说明系统的资源使用情况需要注意了。\n- 这是一个正在测试的指标参数可能需要根据实际情况再优化，如果展示的主机量较多，该查询可能会消耗较多资源引起卡顿，您可以编辑表格，禁用这个查询的promql。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_uname_info{$ext_key=~\"$ext_value\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{$ext_key=~\"$ext_value\"})by(instance)/86400",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{$ext_key=~\"$ext_value\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{$ext_key=~\"$ext_value\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{$ext_key=~\"$ext_value\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{$ext_key=~\"$ext_value\"} / (node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{$ext_key=~\"$ext_value\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{$ext_key=~\"$ext_value\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{$ext_key=~\"$ext_value\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{$ext_key=~\"$ext_value\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{$ext_key=~\"$ext_value\",device=~\"$device\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{$ext_key=~\"$ext_value\",device=~\"$device\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    },
    {
     "expr": "((1-(1 - avg(irate(node_cpu_seconds_total{$ext_key=~\"$ext_value\",mode=\"idle\"}[$interval])) by (instance))^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{$ext_key=~\"$ext_value\"} / node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\"})by (instance))^6)^(1/3)*0.3 + \r\n(1 - max(irate(node_disk_io_time_seconds_total{$ext_key=~\"$ext_value\"}[$interval]))by (instance)^1.1)^(1/2)*0.2)*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(irate(node_disk_io_time_seconds_total{$ext_key=~\"$ext_value\"}[$interval])) by (instance) *100",
     "legendFormat": "IOutil使用率"
    },
    {
     "expr": "max(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) by(instance)",
     "legendFormat": "最大分区容量"
    },
    {
     "expr": "max by(instance,mountpoint)(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}) *100/topk (1,(max by (instance,mountpoint)(node_filesystem_avail_bytes {$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{$ext_key=~\"$ext_value\",fstype=~\"ext.?|xfs\"})))) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最近7天P99资源使用率",
   "type": "table",
   "description": "- P99：数据集按升序排列，第99分位置大的数据。（即升序排列后排在99%位置的数据）\n- 该表格需要在Prometheus增加记录规则（参考看板下载页）\n- 采集1小时后出数据\n- 时间范围[7d:1h]表示要查看过去 7 天内每小时的数据点。\n- node_vmstat_oom_kill需要 Linux 内核版本 4.13及更高版本。",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "node_uname_info{$ext_key=~\"$ext_value\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile_over_time(0.99, cpu:usage:rate1m{$ext_key=~\"$ext_value\"}[7d:1h])",
     "legendFormat": "CPU使用率P99"
    },
    {
     "expr": "quantile_over_time(0.99, mem:usage:rate1m{$ext_key=~\"$ext_value\"}[7d:1h])",
     "legendFormat": "内存使用率P99"
    },
    {
     "expr": "increase(node_vmstat_oom_kill{$ext_key=~\"$ext_value\"}[3d])",
     "legendFormat": "OOM3d"
    }
   ]
  },
  {
   "title": "整体总负载【K8S：$ext_value】",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_load5{$ext_key=~\"$ext_value\"})",
     "legendFormat": "5m负载"
    },
    {
     "expr": "count(node_cpu_seconds_total{$ext_key=~\"$ext_value\",mode='system'})",
     "legendFormat": "核数"
    },
    {
     "expr": "sum(node_load5{$ext_key=~\"$ext_value\"})/count(node_cpu_seconds_total{$ext_key=~\"$ext_value\",mode='system'}) *100",
     "legendFormat": "CPU%"
    }
   ]
  },
  {
   "title": "整体总内存【K8S：$ext_value】",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\"} - node_memory_MemAvailable_bytes{$ext_key=~\"$ext_value\"})",
     "legendFormat": "总已用"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\"} - node_memory_MemAvailable_bytes{$ext_key=~\"$ext_value\"}) / sum(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\"}))*100",
     "legendFormat": "内存%"
    }
   ]
  },
  {
   "title": "整体总磁盘（EXT.*/XFS）【K8S：$ext_value】",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{$ext_key=~\"$ext_value\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总使用量"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总磁盘量"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{$ext_key=~\"$ext_value\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/sum(avg(node_filesystem_size_bytes{$ext_key=~\"$ext_value\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "磁盘%"
    }
   ]
  },
  { "title": "🧮资源明细【$show_name】【$instance】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "分区可用空间(EXT.*/XFS/NFS)",
   "type": "table",
   "description": "本看板中的：磁盘总量、使用量、可用量、使用率保持和df命令的Size、Used、Avail、Use% 列的值一致，并且Use%的值会四舍五入保留一位小数，会更加准确。\n\n注：df中Use%算法为：(size - free) * 100 / (avail + (size - free))，结果是整除则为该值，非整除则为该值+1，结果的单位是%。\n参考df命令源码：",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) * 100",
     "legendFormat": "IOwait使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "最大分区使用率({{mountpoint}})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "- 【最大打开文件数】是统计的node-exporter进程的process_max_fds，如果你的node-exporter是使用systemd启动，那么可能你所有使用systemd方式启动的服务的process_max_fds都是该值。\n- 【OOM次数】node_vmstat_oom_kill需要 Linux 内核版本 4.13及更高版本。\n- 【1h等待时间】PSI 资源压力指标需要 Linux 内核版本 4.20 及更高版本。如果构建您自己的内核，请确保在构建配置中设置 CONFIG_PSI=y 每个资源的压力信息通过/proc/pressure/获取。",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$instance\"})",
     "legendFormat": "运行时间",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'})",
     "legendFormat": "CPU 核",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "总内存",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(increase(node_vmstat_oom_kill{instance=~\"$instance\"}[1d])) or -1",
     "legendFormat": "1天OOM次数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "node_filefd_maximum{instance=~\"$instance\"}",
     "legendFormat": "总文件描述符",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "process_max_fds{job=\"node_exporter\",instance=~\"$instance\"}",
     "legendFormat": "最大打开文件",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "increase(node_pressure_cpu_waiting_seconds_total{instance=~\"$instance\"}[1h])",
     "legendFormat": "CPU1h等待时间",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "increase(node_pressure_io_waiting_seconds_total{instance=~\"$instance\"}[1h])",
     "legendFormat": "IO1h等待时间",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "increase(node_pressure_memory_waiting_seconds_total{instance=~\"$instance\"}[1h])",
     "legendFormat": "内存1h等待时间",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "每分钟流量$device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$instance\",device=~\"$device\"}[1m])",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$instance\",device=~\"$device\"}[1m])",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "总使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "磁盘IO使用率"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "可用"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "使用率：{{mountpoint}}"
    },
    {
     "expr": "(1 - node_filesystem_files_free{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"} / node_filesystem_files{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"}) * 100",
     "legendFormat": "Inodes%：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "1分钟负载"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU总核数"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "15分钟负载"
    }
   ]
  },
  {
   "title": "进程运行状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=~\"$instance\"}",
     "legendFormat": "运行态的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=~\"$instance\"}",
     "legendFormat": "等待IO完成阻塞的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "文件描述符(FD)/每秒上下文切换",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "每秒上下文切换"
    },
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$instance\"}/node_nf_conntrack_entries_limit{instance=~\"$instance\"} * 100",
     "legendFormat": "Conntrack使用占比"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "总使用FD"
    },
    {
     "expr": "(node_filefd_allocated{instance=~\"$instance\"}/node_filefd_maximum{instance=~\"$instance\"}) *100",
     "legendFormat": "总使用FD占比"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）",
   "type": "timeseries",
   "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "timeseries",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每秒磁盘读写容量",
   "type": "timeseries",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗时占比（I/O Util）",
   "type": "timeseries",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "网络Socket连接信息",
   "type": "timeseries",
   "description": "- Sockets_used - 已使用的所有协议套接字总量\n- CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n- TCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n- TCP_tw - 等待关闭的TCP连接数\n- UDP_inuse - 正在使用的 UDP 套接字数量\n- OutSegs - TCP 发送的报文数\n- InSegs - TCP 接收的报文数\n- RetransSegs - TCP 重传报文数\n\n- TcpExt_ListenDrops - 监听队列连接丢弃数\n- TcpExt_ListenOverflows - 监听 socket 的队列溢出\n- Tcp_InErrs - TCP 接收的错误报文数\n- Tcp_OutRsts - TCP 发送的RST报文数\n- TcpExt_SyncookiesSent - 发送的 SYN cookies 的数量\n- TcpExt_SyncookiesRecv - 接收的 SYN cookies 的数量\n- TcpExt_SyncookiesFailed - 无效的 SYN cookies 的数量",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$instance\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$instance\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$instance\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$instance\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$instance\"}[$interval])",
     "legendFormat": "TcpExt_ListenDrops"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$instance\"}[$interval])",
     "legendFormat": "TcpExt_ListenOverflows"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_InErrs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutRsts{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_OutRsts"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$instance\"}[$interval])",
     "legendFormat": "TcpExt_SyncookiesSent"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$instance\"}[$interval])",
     "legendFormat": "TcpExt_SyncookiesRecv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$instance\"}[$interval])",
     "legendFormat": "TcpExt_SyncookiesFailed"
    }
   ]
  },
  {
   "title": "每秒网络带宽使用$device",
   "type": "timeseries",
   "description": "带宽的单位是bit/s",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_out上传"
    },
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"$instance\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}}_in下载丢弃"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"$instance\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}}_out上传丢弃"
    },
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$instance\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}}_in下载错误"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$instance\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}}_out上传错误"
    }
   ]
  }
 ]
}