{
 "title": "KubeDoor - K8S资源实时监控看板",
 "description": "KubeDoor - K8S资源实时监控看板",
 "tags": [
  "StarsL.cn",
  "Kubernetes",
  "KubeDoor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ext_key", "label": "external_labels_key", "query": "__PROM_K8S_TAG_KEY__" },
   {
    "name": "ext_value",
    "label": "K8S",
    "query": {
     "query": "label_values(kube_node_info,$ext_key)"
    }
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(kube_node_info{$ext_key=~\"$ext_value\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_namespace_created{$ext_key=~\"$ext_value\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "微服务(容器名)",
    "query": {
     "query": "label_values(kube_pod_container_info{$ext_key=~\"$ext_value\", namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{$ext_key=~\"$ext_value\", namespace=~\"$namespace\", container=~\"$container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "节点资源总览：所选节点:【$node】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点内存比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "内存请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "内存限制率"
    }
   ]
  },
  {
   "title": "节点CPU比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"}[2m])) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU限制率"
    }
   ]
  },
  {
   "title": "节点与Pod",
   "type": "bargauge",
   "description": "集群节点数，节点POD数，节点POD上限",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{$ext_key=~\"$ext_value\"})",
     "legendFormat": "节点数"
    },
    {
     "expr": "count(kube_pod_info{$ext_key=~\"$ext_value\",created_by_kind!~\"<none>|Job\",node=~\"^$node$\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "title": "命名空间资源统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{$ext_key=~\"$ext_value\",node=~\"^$node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{$ext_key=~\"$ext_value\"}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",$ext_key=~\"$ext_value\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{$ext_key=~\"$ext_value\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{$ext_key=~\"$ext_value\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$namespace：网络总览（可关联节点与命名空间）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{$ext_key=~\"$ext_value\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m]))*8",
     "legendFormat": "接收"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{$ext_key=~\"$ext_value\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m]))*8",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "节点内存信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点CPU核数",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",id=\"/\",node=~\"^$node$\"}[2m]))",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点存储信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) / sum (container_fs_limit_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})",
     "legendFormat": "使用率"
    },
    {
     "expr": "sum (container_fs_usage_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum (container_fs_limit_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})",
     "legendFormat": "总量"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "repeat": "origin_prometheus",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",$ext_key=~\"$ext_value\"})",
     "legendFormat": "工作负载"
    },
    {
     "expr": "count(kube_pod_info{$ext_key=~\"$ext_value\"})",
     "legendFormat": "总Pod"
    },
    {
     "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{$ext_key=~\"$ext_value\",key=~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "count by(origin_prometheus)(kube_node_info{$ext_key=~\"$ext_value\"})",
     "legendFormat": "总节点"
    },
    {
     "expr": "count by(origin_prometheus)(kube_node_info{$ext_key=~\"$ext_value\"}) - count by(origin_prometheus)(kube_node_spec_taint{$ext_key=~\"$ext_value\",key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "正常节点"
    },
    {
     "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{$ext_key=~\"$ext_value\",key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "内存使用量【$node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"})",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "CPU使用核【$node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",id=\"/\",node=~\"^$node$\"}[2m]))",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "Pod数与节点数【$node】",
   "type": "timeseries",
   "description": "集群节点数，节点POD数，节点POD上限",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_node_info{$ext_key=~\"$ext_value\"})",
     "legendFormat": "节点数"
    },
    {
     "expr": "count(kube_pod_info{$ext_key=~\"$ext_value\",created_by_kind!~\"<none>|Job\",node=~\"^$node$\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "title": "$node：节点CPU明细",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node：节点内存明细",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node：节点网络总览",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{$ext_key=~\"$ext_value\",node=~\"^$node$\"}[2m]))by (node) *8",
     "legendFormat": "流入:{{node}}"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{$ext_key=~\"$ext_value\",node=~\"^$node$\"}[2m]))by (node) *8",
     "legendFormat": "流出:{{node}}"
    }
   ]
  },
  {
   "title": "$node：节点信息明细",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(kube_pod_info{$ext_key=~\"$ext_value\",created_by_kind!~\"<none>|Job\",node!=\"\",node=~\"^$node$\"}) by (node)",
     "legendFormat": "pod数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"}[2m])) by (node)"
    },
    {
     "expr": "kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node!=\"\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node!=\"\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"}) by (node) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node!=\"\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node!=\"\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container!=\"\",node=~\"^$node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "CPU使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "CPU请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})by (node) / sum (container_fs_limit_bytes{$ext_key=~\"$ext_value\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})by (node)",
     "legendFormat": "磁盘使用%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{$ext_key=~\"$ext_value\",resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})by (node)",
     "legendFormat": "Pod上限"
    }
   ]
  },
  {
   "title": "node-exporter资源信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "node-exporter：节点1分钟负载",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(node_load1{$ext_key=~\"$ext_value\",instance=~\"$node\"})by(instance,nodeAppType)",
       "legendFormat": "{{nodeAppType}} {{instance}} "
      },
      {
       "expr": "min(count(node_cpu_seconds_total{$ext_key=~\"$ext_value\",instance=~\"$node\", mode='system'}) by (instance,nodeAppType))by(nodeAppType)",
       "legendFormat": "CPU总核数 {{nodeAppType}}"
      }
     ]
    },
    {
     "title": "node-exporter：节点CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{$ext_key=~\"$ext_value\",instance=~\"$node\",mode=\"idle\"}[2m])) by (instance,nodeAppType))*100",
       "legendFormat": "总{{nodeAppType}} {{instance}}"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{$ext_key=~\"$ext_value\",instance=~\"$node\",mode=\"iowait\"}[2m])) by (instance,nodeAppType) *100",
       "legendFormat": "IO {{nodeAppType}} {{instance}}"
      }
     ]
    },
    {
     "title": "node-exporter：节点内存使用量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\",instance=~\"$node\"})by(nodeAppType)",
       "legendFormat": "总内存 {{nodeAppType}}"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\",instance=~\"$node\"} - node_memory_MemAvailable_bytes{$ext_key=~\"$ext_value\",instance=~\"$node\"})by(instance,nodeAppType)",
       "legendFormat": "{{nodeAppType}} {{instance}}"
      }
     ]
    },
    {
     "title": "node-exporter：节点内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\",instance=~\"$node\"} - node_memory_MemAvailable_bytes{$ext_key=~\"$ext_value\",instance=~\"$node\"})by(instance,nodeAppType)/min(node_memory_MemTotal_bytes{$ext_key=~\"$ext_value\",instance=~\"$node\"})by(instance,nodeAppType)",
       "legendFormat": "{{nodeAppType}} {{instance}} "
      }
     ]
    },
    {
     "title": "node-exporter：节点每分钟流入流量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(increase(node_network_receive_bytes_total{$ext_key=~\"$ext_value\",instance=~\"$node\"}[1m]))by(nodeAppType,instance)",
       "legendFormat": "下载 {{nodeAppType}} {{instance}}"
      }
     ]
    },
    {
     "title": "node-exporter：节点每分钟流出流量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(increase(node_network_transmit_bytes_total{$ext_key=~\"$ext_value\",instance=~\"$node\"}[1m]))by(nodeAppType,instance)",
       "legendFormat": "上传 {{nodeAppType}} {{instance}} "
      }
     ]
    },
    {
     "title": "PVC存储使用情况",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{$ext_key=~\"$ext_value\"})",
       "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
      },
      {
       "expr": "min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{$ext_key=~\"$ext_value\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{$ext_key=~\"$ext_value\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{$ext_key=~\"$ext_value\"}) /(min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{$ext_key=~\"$ext_value\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{$ext_key=~\"$ext_value\"}))*100",
       "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
      },
      {
       "expr": "count by (namespace,persistentvolumeclaim)(kube_pod_spec_volumes_persistentvolumeclaims_info{$ext_key=~\"$ext_value\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "各命名空间CPU使用核(>0.1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container!=\"\",container!=\"POD\"}[2m])) by (namespace)>0.1",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "命名空间WSS内存使用(>1G)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container!=\"\",container!=\"POD\"}) by (namespace) > 1*1024*1024*1024",
       "legendFormat": "{{namespace} {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod资源总览：所选Pod:【$pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node：Pod资源明细(可关联节点) $container",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 491 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}/100000) by (container, pod,node,namespace)) "
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace)",
       "legendFormat": "CPU核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container=~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container=~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "wss%"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "wss"
      },
      {
       "expr": "sum (container_memory_rss{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "rss%"
      },
      {
       "expr": "sum (container_memory_rss{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "rss"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container=~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container=~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"} * on (pod) group_left(node) kube_pod_info{$ext_key=~\"$ext_value\",pod=~\"$pod\",node=~\"^$node$\",namespace=~\"$namespace\"}"
      },
      {
       "expr": "time() - kube_pod_created{$ext_key=~\"$ext_value\",pod=~\"$pod\",namespace=~\"$namespace\"} * on(pod) group_right kube_pod_container_info{$ext_key=~\"$ext_value\",pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_fs_limit_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{$ext_key=~\"$ext_value\",pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}) by(pod) *8",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{$ext_key=~\"$ext_value\",pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}) by(pod) *8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod容器CPU使用率(最大100%可关联节点)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 551 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod) / (max(container_spec_cpu_quota{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}/100000) by (container, pod)) * 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod容器内存使用率(可关联节点)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 551 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod)/ max(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod) * 100",
       "legendFormat": "WSS：{{ pod }}"
      },
      {
       "expr": "max (container_memory_rss{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod)/ max(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod) * 100",
       "legendFormat": "RSS：{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod每秒网络带宽 (可关联节点)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 551 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "max(max(irate(container_network_receive_bytes_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{$ext_key=~\"$ext_value\",pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}) by(pod) *8",
       "legendFormat": "流入:{{ pod}}"
      },
      {
       "expr": "max(max(irate(container_network_transmit_bytes_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{$ext_key=~\"$ext_value\",pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}) by(pod) *8",
       "legendFormat": "流出:{{ pod}}"
      }
     ]
    },
    {
     "title": "Pod容器CPU核使用",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 560 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace)",
       "legendFormat": "CPU使用：{{ pod }}"
      },
      {
       "expr": "max(max(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container=~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)) by(container)",
       "legendFormat": "Pod CPU限制：{{ container}}"
      }
     ]
    },
    {
     "title": "Pod容器WSS内存使用(可关联节点)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 560 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "WSS：{{ pod }}"
      },
      {
       "expr": "max(max(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container=~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)) by(container)",
       "legendFormat": "Pod内存限制：{{ container}}"
      }
     ]
    },
    {
     "title": "Pod容器RSS内存使用(可关联节点)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 560 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max (container_memory_rss{$ext_key=~\"$ext_value\",pod=~\"$pod\",container=~\"$container\",container!=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "RSS：{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "微服务(容器名)资源总览：所选微服务:【$container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "微服务(容器名)资源统计",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 492 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}/100000) by (container))"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container)",
       "legendFormat": "总核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "平均内存%(RSS)"
      },
      {
       "expr": "sum (container_memory_rss{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "总内存使用(RSS) "
      },
      {
       "expr": "sum by(container) (kube_pod_container_resource_requests{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"})"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"memory\", unit=\"byte\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "avg(container_fs_usage_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by(container,namespace)"
      },
      {
       "expr": "avg(container_fs_limit_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      }
     ]
    },
    {
     "title": "微服务(容器名)平均CPU使用率(最大100%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 502 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}/100000) by (container)) * 100",
       "legendFormat": "{{ container}}"
      }
     ]
    },
    {
     "title": "微服务(容器名)平均内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 502 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container) * 100",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container) * 100",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "微服务(容器名)每秒网络带宽 (可关联节点)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 502 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{$ext_key=~\"$ext_value\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{$ext_key=~\"$ext_value\",namespace=~\"$namespace\",container=~\"$container\"}) by(container) *8",
       "legendFormat": "流入:{{ container }}"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{$ext_key=~\"$ext_value\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{$ext_key=~\"$ext_value\",namespace=~\"$namespace\",container=~\"$container\"}) by(container) *8",
       "legendFormat": "流出:{{ container }}"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体CPU使用核",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 509 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{$ext_key=~\"$ext_value\",resource=\"cpu\", unit=\"core\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "CPU限制：{{ container}}"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container)",
       "legendFormat": "CPU核使用：{{ container}}"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体内存使用量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 509 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "内存限制：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "微服务(容器名)Pod数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 509 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{$ext_key=~\"$ext_value\",container=~\"$container\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by(container,namespace)",
       "legendFormat": "{{namespace}}：{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}