services:
  victoriametrics:
    container_name: victoriametrics
    image: registry.cn-shenzhen.aliyuncs.com/starsl/victoria-metrics:stable
    ports:
      - 8428:8428
    volumes:
      - /opt/victoriametrics/data:/var/lib/victoria-metrics-data
    command:
      - "--storageDataPath=/var/lib/victoria-metrics-data"
      - "--retentionPeriod=30d"
      - "--httpAuth.username=monit"
      - "--httpAuth.password=dduF1E3sj"
      - "--search.maxQueryLen=655350"

    restart: always
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
