image:
  repository: swr.cn-south-1.myhuaweicloud.com/starsl.cn
  kubedoor_api_tag: 1588-7296d1ff
  kubedoor_web_tag: 1585-635a7495
  kubedoor_webhook_tag: 1562-d3889fb4

kubedoor_web_secret:
  enabled: true # nginx basic认证配置文件的开关，首次部署必须设置为 true 表示创建该文件，用于KuboDoorWeb登录的账号密码创建；之后更新时，可以根据需要设置 false 表示不更新该文件，以防止直接在Secrets配置的用户密码被覆盖。
  nginx_auth: # htpasswd格式："用户名:加密密码"，可以在https://tool.lu/htpasswd/在线生成，加密方式选Crypt。
    - kubedoor:a3rsHbfPnb4Ps # 这是默认的账号密码，都是"kubedoor"，可以配置多个账号。

config: # 调用外部资源的配置信息
  # 这里填写你的ClickHouse的信息，注意网络通讯正常
  CK_HOST: "10.7.0.1" # ClickHouse数据库的IP
  CK_PORT: "9000" # ClickHouse数据库的TCP端口
  CK_HTTP_PORT: "8123" # ClickHouse数据库的HTTP端口
  CK_USER: "default" # ClickHouse数据库的账号
  CK_PASSWORD: "Ub7SrsRG" # ClickHouse数据库的密码

  # 这里填写你的K8S接入监控的时序数据库信息，注意网络通讯正常
  # 请根据你的时序数据库填写类型。
  # 注意：Prometheus默认端口是9090，Victoria-Metrics-Single默认端口是8428，Victoria-Metrics-Cluster默认读端口是8481。
  PROM_TYPE: "Victoria-Metrics-Single" # 从Prometheus中采集数据，输入Prom数据源的类型：Prometheus, Victoria-Metrics-Single, Victoria-Metrics-Cluster
  PROM_URL: "http://ops:passwd@10.7.0.2:8428" #Prometheus的地址，http开头，端口号结尾，有认证的按例子格式填写。

  # 如下两个字段KEY/VALUE是给存储使用非Prometheus的远程存储用的，即为Prometheus设置的extenal_label的key/value。
  # 用于多K8S监控数据写入到同一个时序数据库的场景，使用远程存储时，这种标签会增加到每一个指标中，这样通过这个标签就可以区分出这些指标属于哪个K8S了。
  # 如果你的K8S监控数据采集到了单独的Prometheus（存储就是Prometheus本身的），或者远程存储没有使用区分K8S的标签，请把KEY/VALUE都设置为空""。
  PROM_K8S_TAG_KEY: "origin_prometheus"
  PROM_K8S_TAG_VALUE: "cassmall-gamma"

  # 这里是填写业务相关的信息
  NAMESPACE_LIST: "infra,inquiry,terminal,vip,ops-monit" # 需要采集数据和管控的命名空间列表，所有操作都关联这些命名空间。
  PEAK_TIME: "10:00:00-11:30:00" # 根据业务实际情况设置一个每日的高峰时间段，会采集该时间段的数据，计算P95值，并更新到数据库；不建议设置过长的时间段，因为最终是获取P95数据，所以选择一个业务高峰时间段即可。

  # 这里填写通知的信息
  # 钉钉机器人安全设置的自定义关键词请设置为：告警
  MSG_TYPE: "wecom" # 各类操作通知的消息类型：wecom, dingding, feishu
  MSG_TOKEN: "164xxx98s8-18x0-4dx1-8xe1-980xxxxaaba" # 通知服务对应的token
