image:
  repository: swr.cn-south-1.myhuaweicloud.com/starsl.cn
  kubedoor_agent_tag: 1.0.7
  kubedoor_master_tag: 1.0.5
  kubedoor_alarm_tag: 1.0.2
  kubedoor_web_tag: 1.0.0
  kubedoor_admis_tag: 1.1.0

  grafana_plugins_init: 0.1.0 
  grafana_oss: 11.4.0

kubedoor:
  agent:
    enable: false
  master:
    enable: false
  web:
    enable: false
  dash:
    enable: false
  admis:
    enable: false

clickhouse:
  enable: false

monit:
  vmagent:
    enable: false
  kube_state_metrics:
    enable: false
  node_exporter:
    enable: false
  alertmanager:
    enable: false
  kubedoor_alarm:
    enable: false
  vmalert:
    enable: false
